In [6]:
import pandas as pd

df = pd.read_csv('ANEEL_Dataset.csv')

# Vemos cuántas filas y columnas tiene, y las primeras 5 filas
print(f"Filas: {df.shape[0]} | Columnas: {df.shape[1]}")
df.head()

Filas: 1311 | Columnas: 13

,tipo,usina,tipo_de_leilao,leilao,pot_MW,garantia_fisica_MW_medio,lotes_vendidos,preco_por_MW,localizacao,fonte,mod,invest_previsto,empresa_consorcio
0,UHE,UHE Foz do Rio Claro,A-5,Leilão 2/2005,"68,40","41,00",41,"108,04",Caçú e São Simão/GO,Água,PIE,"281.032.620,00",Alusa Engenharia Ltda
1,UHE,UHE São José,A-5,Leilão 2/2005,"51,00","30,40",30,"115,80",Salvador das Missões e Rolador / RS,Água,PIE,"208.985.970,00",Alusa Engenharia Ltda
2,UHE,UHE Passo São João,A-5,Leilão 2/2005,"77,00","39,00",37,"112,55",Dezesseis de Novembro e Roque Gonzales / RS,Água,PIE,"267.595.880,00",Eletrosul S.A.
3,UHE,UHE Simplício,A-5,Leilão 2/2005,"337,70","191,30",185,"115,38",Sapucaia e Três Rios/RJ e Chiador e Além Paraí...,Água,PIE,"1.441.505.800,00",Furnas\r\nCentrais Elétricas S.A.
4,UHE,UHE Retiro Baixo,A-5,Leilão 2/2005,"82,00","38,50",36,"114,86",Curvelo e Pompeu/MG,Água,PIE,"262.417.880,00",Orteng Equipamentos e Sistemas Ltda.

In [7]:
# Quitar espacios al inicio o final de los nombres de las columnas
df.columns = df.columns.str.strip()

df = df.drop_duplicates()

print("Nombres de columnas limpios:")
print(df.columns.tolist())

Nombres de columnas limpios:
['tipo', 'usina', 'tipo_de_leilao', 'leilao', 'pot_MW', 'garantia_fisica_MW_medio', 'lotes_vendidos', 'preco_por_MW', 'localizacao', 'fonte', 'mod', 'invest_previsto', 'empresa_consorcio']

In [8]:
# cambiamos ',' por '.'
cols_decimales = ['pot_MW', 'garantia_fisica_MW_medio', 'preco_por_MW']
for col in cols_decimales:
    df[col] = df[col].astype(str).str.replace(',', '.')
    df[col] = pd.to_numeric(df[col], errors='coerce') # Convertir a número real

df['invest_previsto'] = df['invest_previsto'].astype(str).str.replace('.', '', regex=False).str.replace(',', '.', regex=False)
df['invest_previsto'] = pd.to_numeric(df['invest_previsto'], errors='coerce')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1311 entries, 0 to 1310
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   tipo                      1311 non-null   object
 1   usina                     1311 non-null   object
 2   tipo_de_leilao            1311 non-null   object
 3   leilao                    1311 non-null   object
 4   pot_MW                    1304 non-null   float64
 5   garantia_fisica_MW_medio  1308 non-null   float64
 6   lotes_vendidos            1311 non-null   object
 7   preco_por_MW              1311 non-null   float64
 8   localizacao               1311 non-null   object
 9   fonte                     1311 non-null   object
 10  mod                       1311 non-null   object
 11  invest_previsto           1204 non-null   float64
 12  empresa_consorcio         1311 non-null   object
dtypes: float64(4), object(9)
memory usage: 133.3+ KB

In [9]:
df = df.dropna(subset=['pot_MW', 'invest_previsto'])

# Crear una nueva columna calculada: ¿Cuánta plata se invirtió por cada MW?
df['invest_por_MW'] = df['invest_previsto'] / df['pot_MW']

df.head()

,tipo,usina,tipo_de_leilao,leilao,pot_MW,garantia_fisica_MW_medio,lotes_vendidos,preco_por_MW,localizacao,fonte,mod,invest_previsto,empresa_consorcio,invest_por_MW
0,UHE,UHE Foz do Rio Claro,A-5,Leilão 2/2005,68.4,41.0,41,108.04,Caçú e São Simão/GO,Água,PIE,2.810326e+08,Alusa Engenharia Ltda,4.108664e+06
1,UHE,UHE São José,A-5,Leilão 2/2005,51.0,30.4,30,115.80,Salvador das Missões e Rolador / RS,Água,PIE,2.089860e+08,Alusa Engenharia Ltda,4.097764e+06
2,UHE,UHE Passo São João,A-5,Leilão 2/2005,77.0,39.0,37,112.55,Dezesseis de Novembro e Roque Gonzales / RS,Água,PIE,2.675959e+08,Eletrosul S.A.,3.475271e+06
3,UHE,UHE Simplício,A-5,Leilão 2/2005,337.7,191.3,185,115.38,Sapucaia e Três Rios/RJ e Chiador e Além Paraí...,Água,PIE,1.441506e+09,Furnas\r\nCentrais Elétricas S.A.,4.268599e+06
4,UHE,UHE Retiro Baixo,A-5,Leilão 2/2005,82.0,38.5,36,114.86,Curvelo e Pompeu/MG,Água,PIE,2.624179e+08,Orteng Equipamentos e Sistemas Ltda.,3.200218e+06

In [10]:
df.to_csv('ANEEL_Dataset_Procesado.csv', index=False)

print("¡Corona! El dataset limpio y está como 'ANEEL_Dataset_Procesado.csv'")

¡Corona! El dataset limpio y está como 'ANEEL_Dataset_Procesado.csv'